version: "3.9"
services:
  mongo:
    image: mongo
  app1:
    build: 
      context: app1
      dockerfile: Dockerfile
    image: jbcontainertst.azurecr.io/test/app1
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 100M
    # volumes:
    #   - static-content:/var/www/app1-static
  app2:
    build:
      context: app2
      dockerfile: Dockerfile
    image: jbcontainertst.azurecr.io/test/app2
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 100M
    #volumes:
      # - static-content:/var/www/app2-static
  ngninx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    image: jbcontainertst.azurecr.io/test/nginx
    domainname: "myapp"
    ports:
      - 80:80
    depends_on:
      - app2
      - app1
# volumes:
#   static-content: